### ISSUE TITLE
Doesn't delay Facebook

### ISSUE THREAD

**Issue by MarkEstefanos** [tfausak/delay#12]
Somehow Facebook manages to bypass the filter. I've tried facebook.com, www.facebook.com, and https://www.facebook.com.

EDIT: Looks like this is an issue with all HTTPS sites.

**Comment by tfausak** [comment]
Delay works for me on every HTTPS site I tested. It doesn't work with Facebook. Interestingly, if you visit Facebook and then refresh, it works.

**Comment by tfausak** [comment]
I'm not super motivated to fix this because Delay is no longer listed on the [Safari Extensions Gallery](https://safari-extensions.apple.com). They changed it from a free service to a paid one like the iOS App Store. 

That being said, I think you can work around this by using the whitelist instead of the blacklist.
